# test against node version
environment:
    matrix:
    # node.js
    - nodejs_version: "8"

# install scripts after repo cloning
install:
    - ps: Install-Product node $evn:nodejs_version
    - npm install

test_script:
    - node --version
    - npm --version
    - npm test

#don't actually build
build: off

